### ISSUE TITLE
data table migrations

### ISSUE THREAD

**Issue by wynot** [wynot/bizmarkio_app#10]
1. Add Teams table with appropriate dimensions & migrate - done
2. Add team_id to user table & migrate - done
3. Add "response" fields to Microposts table & migrate - done
4. Rename Microposts table to "Responses" and correct the namespace in the site to keep functionality working. - done
     ( name change using this: http://stackoverflow.com/questions/4826879/how-to-re-name-a-activerecord-model-which-can-automatically-change-the-table-nam )

5. Add Forms table with right dimensions & migrate - done
6. Create appropriate relationships between Teams and Users etc (has_many, is_a) - done
7. edit seeds file so teams exist
8. set up pull request and review with baishi before merging

leaving vestigial Micropost fields in place. We will eventually want to clean that up.

**Comment by wynot** [comment]
5. Add Forms table with right dimensions & migrate

**Comment by baishiwu** [comment]
See update to #8

**Comment by wynot** [comment]
- Create appropriate relationships between Teams and Users etc (has_many, is_a)

- edit seeds file so teams exist

**Comment by wynot** [comment]
set up pull request and review with baishi before merging

**Comment by wynot** [comment]
name change using this: http://stackoverflow.com/questions/4826879/how-to-re-name-a-activerecord-model-which-can-automatically-change-the-table-nam

**Comment by wynot** [comment]
leaving vestigial Micropost fields in place. We will eventually want to clean that up.

**Comment by wynot** [comment]
Some thinking about the logic:

If 'Form has_many 'Responses', then every response will belong to a form template, not a form instance. So if the user who creates a form deletes his account, all of the responses will be deleted too, even if every other team member exists.

This makes me think we should have a Form_Instance table. But I don't want to add that complexity.

So instead I'm going to have forms "belong" to teams. that way the responses get deleted only if the team is deleted. Seems more conservative for now.

There may be an edge case in the future when a user wants to delete their account and they have the expectation that their feedback be deleted as well, but that won't happen how I'm setting it up.

**Comment by wynot** [comment]
all done. pull request here: https://github.com/wynot/bizmarkio_app/pull/14
