### ISSUE TITLE
Mailer: User is able to send an email to an e-mail address selected

### ISSUE THREAD

**Issue by baishiwu** [wynot/bizmarkio_app#4]
1. i.e. blank page + input form for e-mail + submit > user can receive email from this
2. e-mail is able to pull static data bizmark.io
3. e-mail renders a test partial that contains form data

**Comment by wynot** [comment]
Step One done: generic email sender to arbitrary recipient is live: https://bizmarkiotest.herokuapp.com/sendform

**Comment by wynot** [comment]
(notes for myself)

Plan for 2 & 3:

2. static data will be the "Sender Name", so the content will say something like: "*Bob* has sent you a message!". Simple, but demonstrates database query.
3. sender can select one of two forms to send using radio buttons on the page. Then the email will render either one form or the other.
    - technically, since only one argument can be passed through the controller (I think) the POST parameters from the form need to be passed as an array stored as a variable (maybe "form_params"). This may require defining "form_params" in the user controller, as was done for the New User operation

**Comment by wynot** [comment]
if/then logic for number 2 should exist in the users_controller.rb file in the generic_email function

**Comment by wynot** [comment]
Now launched at https://bizmarkiotest.herokuapp.com/

#done
http://i.giphy.com/10kZ28GnRiDiI8.gif

**Comment by baishiwu** [comment]
![screen shot 2015-01-18 at 10 02 09 pm](https://cloud.githubusercontent.com/assets/1470982/5796487/af3ab4ba-9f5d-11e4-8813-3a5800b7c470.png)

Very cool. From what I can tell, you 1) can't "submit" a response with the multiple choice and 2) you can't submit at all yet. 

(also, love the passive aggressive messages. keep 'em coming!)

**Comment by wynot** [comment]
Right. There's no model built yet to handle response data, so I left that functionality untouched. Next steps could be


1) build out feedback data model (per ERD) and migrate database




Then 




2) create logic to handle response data via email


--
willyoung.me
