### ISSUE TITLE
Migrate app to bizmark.io domain

### ISSUE THREAD

**Issue by baishiwu** [wynot/bizmarkio_app#7]

**Comment by wynot** [comment]
#done

although there appears to be some issue with the SSL security certificate because the certificate is from a different domain. that might be a problem we have to resolve.

**Comment by baishiwu** [comment]
Oops, going to close this again as we likely do not want to pay for the SSL Endpoint add-on that Heroku offers ($20 / month) to solve this issue right now.

http://support.dnsimple.com/articles/ssl-certificate-with-heroku/
