### ISSUE TITLE
Bizmark.io ERD

### ISSUE THREAD

**Issue by baishiwu** [wynot/bizmarkio_app#8]

**Comment by baishiwu** [comment]
![screen shot 2015-01-16 at 10 46 39 am](https://cloud.githubusercontent.com/assets/1470982/5782055/fac706c4-9d6c-11e4-92d2-01d7e398bb59.png)

Example from Jason

**Comment by wynot** [comment]
I took a stab at ERD progression we can use as we develop. Feel free to change as you see fit

https://docs.google.com/presentation/d/1aoAIxx7VihNf5sNPMCzoy-hw_AUMJhXFxcpLV5-bbdw/edit#slide=id.g5d5b34375_057

**Comment by baishiwu** [comment]
![screen shot 2015-01-20 at 4 33 50 pm](https://cloud.githubusercontent.com/assets/1470982/5829126/2b3dac10-a0c2-11e4-99ea-0bb4da9958d0.png)

Updated the last slide to reflect our discussion last night. Here are the discrete changes I've thought of:
* Microposts > Responses. There's no reason to change this, but we can add more fields like who sent out each response.
* Multiple Responses = Form. Having multiple fields that can be variable won't work / scale. Essentially, each question should be a table entry with many that correspond to a single form. This way you can have form 2 consisting of response 3, response 6, response 9.
* Two more things that we might need are 1) a separate table indicating the different types of modules / responses, but if we are using built-in html form type capabilities we may be able to avoid this; 2) some type of reminder structure (eventually)

I think there are other complications in terms of how this relates to controllers re: veiw permissions, aggregations, etc. but that's all I have for now.
